// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfIUMgozRxZUHN7iJUacJQvQ0bT5uROuE',
    appId: '1:984523106114:web:c0e4d8de89e1e412c44adb',
    messagingSenderId: '984523106114',
    projectId: 'hackaton-847ed',
    authDomain: 'hackaton-847ed.firebaseapp.com',
    storageBucket: 'hackaton-847ed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe82uInZZPA4lXtVUlPPz4YNpkQqJowMA',
    appId: '1:984523106114:android:e4399d9c410f4c42c44adb',
    messagingSenderId: '984523106114',
    projectId: 'hackaton-847ed',
    storageBucket: 'hackaton-847ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRPWvhPfNRBXIB-525-CzLua3QKA5W1Og',
    appId: '1:984523106114:ios:1f86f8ca116eac80c44adb',
    messagingSenderId: '984523106114',
    projectId: 'hackaton-847ed',
    storageBucket: 'hackaton-847ed.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRPWvhPfNRBXIB-525-CzLua3QKA5W1Og',
    appId: '1:984523106114:ios:1f86f8ca116eac80c44adb',
    messagingSenderId: '984523106114',
    projectId: 'hackaton-847ed',
    storageBucket: 'hackaton-847ed.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfIUMgozRxZUHN7iJUacJQvQ0bT5uROuE',
    appId: '1:984523106114:web:7eb66a10a84c78c4c44adb',
    messagingSenderId: '984523106114',
    projectId: 'hackaton-847ed',
    authDomain: 'hackaton-847ed.firebaseapp.com',
    storageBucket: 'hackaton-847ed.firebasestorage.app',
  );
}
